jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysql --user=root --password=root --host=127.0.0.1 -e 'SHOW DATABASES;'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer

      - name: Instalar dependências do Laravel
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Criar arquivo .env
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env
          php artisan key:generate

      - name: Aguardar MySQL iniciar
        run: |
          while ! mysql --host=127.0.0.1 --user=root --password=root --silent -e 'SHOW DATABASES;'; do
            echo "Aguardando MySQL..."
            sleep 2
          done

      - name: Limpar cache
        run: |
          cd /home/runner/work/Ger_med/Ger_med # Garantindo que está no diretório correto
          php artisan config:clear
          php artisan cache:clear
          composer dump-autoload

      - name: Rodar migrations
        run: |
          cd /home/runner/work/Ger_med/Ger_med # Garantindo que está no diretório correto
          php artisan migrate --force

      - name: Instalar Dusk e configurar navegador
        run: |
          cd /home/runner/work/Ger_med/Ger_med # Garantindo que está no diretório correto
          php artisan dusk:install
          php artisan dusk:chrome-driver --detect
          echo "APP_URL=http://localhost" >> .env
          export DISPLAY=:99
          sudo apt-get install -y libx11-dev libgdk-pixbuf2.0-dev
          Xvfb :99 -screen 0 1280x1024x16 &  # Inicia um servidor X virtual (para headless)

      - name: Rodar servidor Laravel na porta 8080 em segundo plano
        run: |
          php artisan serve --port=8080 &  # Rodar servidor Laravel na porta 8080 em segundo plano
          sleep 5  # Espera o servidor subir

      - name: Rodar testes do Laravel Dusk
        run: |
          cd /home/runner/work/Ger_med/Ger_med # Garantindo que está no diretório correto
          php artisan dusk
